language: scala
sudo: false

scala:
  - 2.11.12
  - 2.12.8
jdk:
  - oraclejdk8

stages:
  - name: test
  - name: release
    if: (tag IS present) AND NOT fork

jobs:
  include:
    # stage="test" if no stage is specified
    - env:
        - TARGET=JVM PRE=test:compile
        - TARGET=JS  PRE=test:fastOptJS
      script:
        - sbt ++$TRAVIS_SCALA_VERSION ${TARGET}/$PRE
        - sbt ++$TRAVIS_SCALA_VERSION ${TARGET}/test
    # run ci-release only if previous stages passed
    - stage: release
      script: sbt ci-release

cache:
  directories:
    - $HOME/.sbt/1.0/dependency
    - $HOME/.sbt/boot/scala*
    - $HOME/.sbt/launchers
    - $HOME/.ivy2/cache
    - $HOME/.coursier

before_cache:
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
  - rm -rf $HOME/.ivy2/local

before_install:
  - git fetch --tags

