language: scala
jdk:
  - oraclejdk8

scala:
  - 2.12.8
  - 2.11.12

env:
  - TARGET=JVM PRE=test:compile
  - TARGET=JS  PRE=test:fastOptJS

script:
  - sbt ++$TRAVIS_SCALA_VERSION ${TARGET}/$PRE
  - sbt ++$TRAVIS_SCALA_VERSION ${TARGET}/test

stages:
  - name: test
  - name: release
    if: (tag IS present) AND NOT fork

jobs:
  include:
    - stage: release
      env:
      script: sbt ci-release

cache:
  directories:
    - $HOME/.sbt/1.0/dependency
    - $HOME/.sbt/boot/scala*
    - $HOME/.sbt/launchers
    - $HOME/.ivy2/cache
    - $HOME/.coursier

before_cache:
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
  - rm -rf $HOME/.ivy2/local

before_install:
  - git fetch --tags

